[project]
name = "MCP-geo"
dynamic = ["version"]
description = "Geocoding MCP server with GeoPY!"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=0.4.1",
    "geopy>=2.4.1",
]


[tool.hatch.version]
path = "geo.py"